config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: 'islands#index'

  resources :islands, except: :index do
    resources :producers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :producers, dependent: :destroy
  # accepts_nested_attributes_for :producers

  validates :island_name, uniqueness: true, presence: true
  validates :island_country, presence: true

  # validates_associated :producers
  has_one_attached :photo
end

app/models/producer.rb
class Producer < ApplicationRecord
  belongs_to :user
  belongs_to :island

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_one :producer, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show, :new, :create]

  before_action :set_island, only: [ :show, :edit, :update, :destroy]
  # before_action :set_producer, only: [ :show, :edit, :update, :destroy]

  def index
    # @islands = Island.all
    @islands = policy_scope(Island)
  end

  def show
  end

  def new
    @island = Island.new
    authorize @island
  end

  def create
    @island = Island.new(island_params)
    authorize @island
    if @island.save!
      redirect_to island_path(@island), notice: "Island successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @island.update(island_params)
      redirect_to island_path(@island), notice: "Island updated!"
    else
      render :new
    end
  end

  def destroy
    @island.destroy
  end

  private

  def set_island
    @island = Island.find(params[:id])
    authorize @island
  end

  def island_params
    params.require(:island).permit(:island_name, :island_country, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about, :contact ]

  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  before_action :set_island
  before_action :set_producer, only: [ :show, :edit, :update, :destroy]

  def index
    # NOT WORKING
    # @producers = Producer.all
    # @producers = Producer.where(island_id: params[:island_id])
    # @producers = policy_scope(Producer)

    # WORKING >> I needed revise the policy_scope after integrating the Pundit gem for authorization
    @producers = policy_scope(@island.producers)
  end

  def show
  end

  def new
    @producer = Producer.new
    authorize @producer
  end

  def create
    @producer = @island.producers.create(producer_params)
    # redirect_to island_path(@island)
    @producer.user = current_user
    authorize @producer
    # WORKING >> REDIRECTING TO ISLAND SHOWPAGE
    if @producer.save!
      redirect_to island_producer_path(@island, @producer), notice: "Producer was successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @producer.update!(producer_params)
      redirect_to island_producer_path, notice: "Edits saved!"
    else
      render :edit
    end
  end

  def destroy
    @producer.destroy
    redirect_to island_producers_path, notice: "the producer has been removed."
  end

  private

  def set_island
    @island = Island.find(params[:island_id])
  end

  def set_producer
    @producer = @island.producers.find(params[:id])
    authorize @producer
  end

  # delete? >> keeping in efforts to debug index view
  def island_params
    params.require(:island).permit(:island_name, :island_country)
  end

  def producer_params
    params.require(:producer).permit(:producer_name, :email, :address1, :address2, :postal_code, :city, :country, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/islands/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h3>Island details:</h3>
      <%= form_with(model: [ @island ], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :island_name %>
          <%= form.text_field :island_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :island_country %>
          <%= form.text_field :island_country, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :photo %>
        </div>
        <%= form.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/islands/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Edit the Island: <%= @island.island_name %></h1>
    </div>
  </div>
</div>
<%= render 'islands/form', island: @island %>

app/views/islands/index.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'gustoHop-banner.jpg' %>); padding: 100px;">
  <div class="container">
    <div class="container headline">
      <h1>Discover Island wines</h1>
      <em>
        <h3>take a trip in every sip!</h3>
      </em>
      <em>
        <h3>search wines from one of our island producers</h3>
      </em>
    </div>
  </div>
</div>
<div class="banner">
  <div class="container value-add">
    <p>Island wines have several benefits that any wine enthusiast would appreciate. Many are grown within unique microclimates in volcanic soil that imparts distinct characteristics. Furthermore, these wines are grown on small-yield vineyards that utilize organic production methods. We can all toast to that - <em>cin cin!</em>   &#129346;</p>
  </div>
</div>
<div class="banner">
  <div class="container call-to-action">
    <h3>WANT TO LIST YOUR WINE?</h3>
    <a href="mailto:info@gustohop.com" class="btn btn-primary">CONTACT US!</a>
  </div>
</div>
<div class="container island-cards">
  <div class="card-columns">
    <% @islands.each  do |island| %>
      <div class="card">
        <!-- <img class="card-img-top" src="https://kitt.lewagon.com/placeholder/cities/random" alt="Card image cap"> -->
        <% if island.photo = "" %>
          <!-- <p>no image uploaded...</p> -->
          <%= image_tag "island-wine.jpg", class: "card-img-top", alt: 'gustoHop Island Wines' %>
        <% else %>
          <%= cl_image_tag island.photo.key %>
        <% end %>
        <div class="card-body">
          <h3><%= island.island_name %></h3>
          <a href=<%= island_path(island) %> class="btn btn-primary">More Info</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/islands/new.html.erb
<div class="container add-content">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Add an Island!</h1>
    </div>
  </div>
  <%= render 'islands/form', island: @island %>
</div>

app/views/islands/show.html.erb
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 offset-sm-2">
        <h1><%= @island.island_name %> - <em>(<%= @island.island_country %>)</em></h1>
        <% if @island.producers.empty? %>
          <p>There are no producers listed for this island, yet.</p>
          <span>
            <h5>
              <%= link_to "ADD Producer", new_island_producer_path(@island) %>
            </h5>
          </span>
        <% else @island.producers.any? %>
          <span>
            <h4>Producers from <%= @island.island_name %></h4>
          </span>
          <span>
            <h5>
              <%= link_to "ADD Producer", new_island_producer_path(@island) %>
            </h5>
          </span>
          <hr>
          <ul>
            <% @island.producers.each do |producer| %>
              <div class="container">
                <h5><%= producer.producer_name %></h5>
              </div>
            <% end %>
          </ul>
          <hr>
          <h5>
            <%= link_to "View all", island_producers_path(@island) %>
          </h5>
          <h5>
            <% if current_user.try(:admin?) %>
              <%= link_to "EDIT", edit_island_path(@island) %>
            <% end %>
          </h5>
          <h5>
            <% if current_user.try(:admin?) %>
              <%= link_to "DELETE", island_path, method: :delete, data: {confirm: "Are you sure you want to delete this ISLAND? (it is permanent)"} %>
            <% end %>
          </h5>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>gustoHop</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- <style>
      @import url('https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;600;700&display=swap');
    </style> -->
    <%= favicon_link_tag asset_path('gustoHop-favicon.png') %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<p>this is the pages#home</p>
<p>find us in the views/pages/home.html.erb</p>

app/views/producers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h3>Producer details:</h3>
      <%= form_with(model: [ @island, producer ], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :producer_name %>
          <%= form.text_field :producer_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :address1 %>
          <%= form.text_field :address1, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :address2 %>
          <%= form.text_field :address2, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :postal_code %>
          <%= form.text_field :postal_code, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :city %>
          <%= form.text_field :city, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :country %>
          <%= form.text_field :country, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :photo %>
        </div>
        <%= form.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/producers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h2>Edit a Producer</h2>
    </div>
  </div>
</div>
<%= render 'producers/form', producer: @producer %>

app/views/producers/index.html.erb
<div class="container">
  <h1>Producers from <%= @island.island_name %></h1>
  <table>
    <thead>
      <tr>
        <th>
          <h3>NAME</h3>
        </th>
        <th>
          <h3>DETAILS</h3>
        </th>
        <th colspan="10"></th>
      </tr>
    </thead>
    <tbody>
      <% @producers.each do |producer| %>
        <tr>
          <td><%= producer.producer_name %></td>
          <td>
            <%= link_to "more info", island_producer_path(producer.island, producer)%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "ADD Producer", new_island_producer_path, :class => "btn btn-primary" %>
</div>

app/views/producers/new.html.erb
<div class="container add-content">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Add a producer</h1>
    </div>
  </div>
  <%= render 'producers/form', producer: @island.producers.build %>
</div>

app/views/producers/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <div class="container">
        <h2><%= @producer.producer_name %></h2>
        <div class="container">
          <p><%= @producer.address1 %></p>
          <p><%= @producer.address2 %></p>
          <p><%= @producer.city %></p>
          <p><%= @producer.postal_code %></p>
          <p><%= @producer.country %></p>
          <p>ISLAND: <%= @producer.island.island_name %></p>
          <% if @producer.photo = "" %>
            <!-- <p>no image uploaded...</p> -->
            <%= image_tag "producer-image.jpg", style: "height: 180px", alt: 'gustoHop Island Wines' %>
          <% else %>
            <%= cl_image_tag @producer.photo.key %>
          <% end %>
        </div>
        <% if policy(@producer).edit? %>
          <%= link_to "EDIT", edit_island_producer_path(@island, @producer), {class: "btn btn-primary"} %>
        <% end %>
        <% if policy(@producer).destroy? %>
          <%= link_to "DELETE", island_producer_path, method: :delete, data: {confirm: "Are you sure you want to delete? (it is permanent)"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="d-flex flex-column">
  <footer class="footer footer-style">
    <div class="container">
      <div>
        <span>gustoHop &copy; 2020</span>
      </div>
      <div class="ml-auto">
        <span>designed by </span>
        <a href="http://anderskiss.com">Anders Kiss</a>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_url do %>
    <%= image_tag "gustoHop.png", alt: '', id:"brand-image" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <!--         <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "account_avatar.png", alt: '', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!--             <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %> -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>